spring:
  config:
    activate:
      on-profile: dev

management:
  health.db.enabled: false
  endpoints:
    web:
      exposure:
        include: refresh
---
springdoc:
  version: 1.0.0
  swagger-ui:
    url: /open-api.yml
  api-docs:
    enabled: false
spring:
  profiles: dev
besu:
  rpcEndpoints:
  - http://validator1.v2pjxvwalnq.dev-1.wbp.in.wal-mart.com:80
  wallet:
    path: /Users/k0k07q2/Documents/Walmart/eth-connector/wallet-file/3198bc9c-6672-5ab3-d9954942343ae5b6.json
    password: testpassword
  gasPrice: 1000
  gasLimit: 70000
  client:
    rest:
      apikey: gh789hjj
kafka:
  integration-points:
    -
      brokerHost: localhost:9093
      groupId: besu-consumer
      topic: besu-integration-topic1
    -
      brokerHost: localhost:9094
      groupId: besu-consumer
      topic: hlf-integration-topic2
  event-listener:
    brokerHost: localhost:9093
    topic: besu-offchain-topic
events:
  block: true
  smartContract:
  - "0x6Ba72e179b7137B4E844A90af14f9Efb0bE3C11d"
